// To run this file:
// node src/JavaScript/Practice/23_TutorialTwentyThree.js

// Synchronus and Asynchronus behavior in JavaScript

/*
    1) Synchronus Programming in JavaScript:
    -> In synchronus programming, JavaScript executes code in a linear and sequential manner.
       Each line of code is executed one after the other, and the program waits for each operation to complete before moving on to the next.
       This can lead to "blocking" behavior, where long-running operations can cause the entire program or user interface to become unresponsive until those operations finish. 
    2) Asynchronus Programming in JavaScript:
    -> In asynchronus programming, JavaScript allows tasks to be started and cntinue in the background while the program executes other code.
       This is especially useful for tasks that may take some time, like fetching data from a server or reading files.
*/

// Example of Synchronus behavior in JavaScript:
console.log("Start of Synchronus Example");
for (let i = 0; i < 2; i++) {
    // Simulating a time-consuming task
    for (let j = 0; j < 10; j++) {
        console.log( j + " Processing..." ); // This will print "Processing..." multiple times, simulating a delay
    }  
}
console.log("End of Synchronus Example");
/*
    Output:
    Start of Synchronus Example
    0 Processing...
    1 Processing...
    2 Processing...
    3 Processing...
    4 Processing...
    5 Processing...
    6 Processing...
    7 Processing...
    8 Processing...
    9 Processing...
    0 Processing...
    1 Processing...
    2 Processing...
    3 Processing...
    4 Processing...
    5 Processing...
    6 Processing...
    7 Processing...
    8 Processing...
    9 Processing...
    End of Synchronus Example
*/

// Example of Asynchronus behavior in JavaScript:
console.log("Start of Asynchronus Example");   
setTimeout(() => {
    console.log("This message is printed after a delay of 2 seconds");
}, 2000); // 2000 milliseconds = 2 seconds

console.log("End of Asynchronus Example"); 
/*
    Output:
    Start of Asynchronus Example
    End of Asynchronus Example
    This message is printed after a delay of 2 seconds
*/
